apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: flask-web
  ports:
    - port: 80         # External Port
      targetPort: 5000 # Container Port
      nodePort: 30005  # We will access via localhost:30005