apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsolutions-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsolutions
  template:
    metadata:
      labels:
        app: devsolutions
    spec:
      containers:
      - name: devsolutions-app
        image: devsolutions-app:2   # <--- Using the tag '2' you confirmed exists
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:                          # <--- LOOK HERE! It must be 'env', NOT 'environment'
        - name: REDIS_HOST
          value: "redis-service"